### PR TITLE
Expand readme and minor improvements

### PR DESCRIPTION
**Pull request by con-f-use**
I expanded the readme a bit and added useful information.

I also created this `dev` branch, We can commit to it, if we don't want to risk changing the `master` branch. I think it is a good idea at this point. We can test code and discuss stuff here, before we change the (somewhat) stable `master` branch. Also if we merge with the `--squash` option, we don't clod the commit history of master with many commits that just changed small things. They will just exist in `dev` and master will see one large commit. See notes in the expanded readme.

This also gives Charles a way to review changes.

Hope, @cnlohr thinks this is a good idea. I think we could almost tag one of the near-future commits with a version number like `v0.8` and mark it 'stable', 'recommended' or 'pre-release', if we cared to.

### CODE REVIEW

**Comment by cnlohr** [comment]
Won't be able to work on this until about 8 hours from now, but, I did want to mention.  I don't think we need to worry about experimenting in master because the projects all tie to their respective version of the repo.  There are some things in the issue list that would break projects until they get converted.   That seems OK to me because the projects will continue to work anyway.

Other than that, I am unfamiliar with the idea of tagging, etc.  So, I would probably need to see you do it for understanding etiquette.

Last notes: I /really/ need to bang these issues on that list out.  Shouldn't take more than 2 hours.  But... then it would mean another day before posting the video showing the USB demo.

**Comment by con-f-use** [comment]
Tagging is more for the top-level projects, where you would included (well tested) binaries. I will use the dev-branch anyway because I mostly make small changes and many of them. They usually don't justify their own commits. Also I want you to have the last say in your project.

**Comment by cnlohr** [comment]
Gorgeous changes!

**Comment by cnlohr** [comment]
Wait a minute!  I thought these were changes being pushed to main from dev... Did I just goof?  Should we just be incrementally pushing dev into main?  I guess I will live in dev, then we push to main periodically?

**Pull request merged**
