### PR TITLE
General Cleanup

### PR DESCRIPTION
**Pull request by AEFeinstein**
Looks like I did this a while back and never upstreamed it

### CODE REVIEW

**Comment by cnlohr** [comment]
@con-f-use any opinions?  Any reason not to merge?

**Comment by cnlohr** [comment]
@AEFeinstein apart from any complaints from @con-f-use I would like to merge this.

**Comment by AEFeinstein** [comment]
I'm certainly not going to complain!

**Comment by cnlohr** [comment]
I'm still gonna give con-f-use another few days to comment.

**Comment by AEFeinstein** [comment]
Clearly no rush

**Comment by con-f-use** [comment]
Heh, con-f-use was sleeping on the job. Don't have complains, mostly due to having no idea anymore what I did back then :roll_eyes: .

**Comment by cnlohr** [comment]
A vote of confidence if I've ever heard one.

**Pull request merged**
