### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by cnlohr**

### CODE REVIEW

**Comment by con-f-use** [comment]
> I made a ton of changes.  Most of the big functional changes I
wanted to make in esp82xx are in (At least the important ones).  Take
a look if you get time.  I hope you have been able to test things out
on a better module!

Great changes! Looks alot cleaner now. As mentioned, I got my NodeMCU and modules. As my luck would have it, I had to change the ESP on the Node because shipping damge :-/
But, everything works now, and I had a chance to test your changes. No problems so far! It's soooo much nicer to flash firmware over the network. Also no button-presses!

Small things: 
 - I added a hotfix because an include was missing on OSX systems
 - The name for the `ParamCaptureAndAdvanceInt(...)` functions is a bit long. Most C programmers know the [strtok(...)](http://www.cplusplus.com/reference/cstring/strtok/) function, that does basically the same. You could call them `strtok_int(...)`.

**Comment by cnlohr** [comment]
You know, I've never heard of ```strtok``` It does look like it solves a different problem, though.  

This function "pops" a parameter off the global parameter stack, and reports whether it was successfully popped.  

I do agree the function name is pretty awful.

Also, the implementation leaves a lot to be desired.  Do you know if there's any way to pass variables by register-reference in GCC?  Google wasn't too clear on this, but, on the lx106, parameters are passed by register.  If I could update those registers and accept the different values in the caller, that would be the best of every world.  The problem is when I passed them in as pointers the code size ballooned because GCC was constantly trying to push these things on the stack, make references to them and everything was just crazy. 

Hmm, now I wonder if I can "trick" gcc into believing it's passing the registers by value and changing them anyway.

**Comment by con-f-use** [comment]
> This function "pops" a parameter off the global parameter stack, and reports whether it was successfully popped. 

Exactly what `strtok(...)` does.

And sorry no idea how to pass by register-reference. Not even sure what you mean :'(

**Comment by cnlohr** [comment]
Hmm, I guess what I have is pretty close to that, then!  I wonder if it would be more memory-efficient to just implement strtok.  Only thing it doesn't do would be the whole argument-counting I do.

Re: Register-reference.  I don't know what you would call it, but the lx106 architecture passes parameters in registers.  I wish I could tell GCC "hey, that register, keep using it once you're done, don't save it or back it up or anything.  Trust me.  I'm an engineer."

**Pull request merged**
