### PR TITLE
Fix escape bug, when building page

### PR DESCRIPTION
**Pull request by con-f-use**
Little bug when building page from template variables in `user.cfg` now fixed (slashes need too be escaped for `sed`). In the long run the sed command's should be replaced by a proper templating program.

### CODE REVIEW

**Comment by cnlohr** [comment]
I don't think it's possible to treat the webpage like this considering how different each webpage is.

**Comment by cnlohr** [comment]
We need to talk about the webpage being updated this way.

**Comment by con-f-use** [comment]
Yes, most projects will need their own `index.html`, but for small changes it should be okay considering you can also include a `<script>`-tag this way. 

I just needed a way to flash the same firmware to different modules, with just the title of the page changing slightly between each modules. So it was:
```
make burnweb "PAGE_TITLE=Module 1"
make burnweb "PAGE_TITLE=Module 2"
...
make burnweb "PAGE_TITLE=Module 6"
```

**Comment by cnlohr** [comment]
I'll give it a shot.

**Comment by cnlohr** [comment]
ColorChord seems not to be importing esp82xx, even when I 

```
 git pull --recurse-submodules
````

**Comment by cnlohr** [comment]
Ok, nevermind. 

```
git submodule update --init --recursive
```

Did the trick. 

Odd problem, though.  It seems to be trying to go with git:// rather than https://

**Comment by cnlohr** [comment]
Yeah, this is totally not working

```
Cloning into 'embedded8266/esp82xx'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by con-f-use** [comment]
Ah, yes the endless fun that is git. I think it's trying to authenticate with ssh and failing. The problem might be the `.gitmodules` file:

```
[submodule "embedded8266/esp82xx"]
    path = embedded8266/esp82xx
    url = git@github.com:cnlohr/esp82xx.git
```

**Comment by cnlohr** [comment]
Hmm, I don't really get this... It didn't work when I had a .git at the end, but when I  took the .git off, it failed.  I can't figure out what's going on there... I did find out I had to re-build my esp-open-sdk, so that's going right now.

```
[submodule "embedded8266/esp82xx"]
        path = embedded8266/esp82xx
        url = https://github.com/cnlohr/esp82xx
```

Perhaps it was a one-off problem?

**Comment by con-f-use** [comment]
Internet says it should be `url = https://github.com/cnlohr/esp82xx.git`, but no idea. I never had this problem before.

**Comment by cnlohr** [comment]
Ok, got that.  Now, if I can get colorchord working (after my esp open SDK is done), then I will move onto another module.

**Comment by con-f-use** [comment]
Why do you have to rebuild your sdk? Maybe the wrong path is just set in the makefile?

Anyway gotta go to sleep, I'm dead tired. Will look at github first thing tomorrow. Cheers.

**Comment by cnlohr** [comment]
yeah, you had 1.5.4, I was on 1.5.2... but, now the SDK its set up to use is too new and can't fit colorchord :( :( :(

```
/home/cnlohr/esp8266/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin
/ld: image.elf section `.text' will not fit in region `iram1_0_seg'
/home/cnlohr/esp8266/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin
/ld: region `iram1_0_seg' overflowed by 1056 bytes
```

I'll try to get this moving, I hope it'll all be done when you wake up.

**Comment by con-f-use** [comment]
Actually I was on 1.5.0 because I had the exact same error with 1.5.4

**Comment by cnlohr** [comment]
Two things

(1) I have made a number of minor changes, allowing some things to be specified in slightly different ways, like increasing the burn baud rate, always rebuilding webpage, adding paths in-line, etc.

(2) What do you want on the copyright?  A great deal of this is yours.

(3) So you are aware, the ESPs can nominally find each other, too!  And on smaller projects we can use mdns.  To find other ESPs, send broadcast 'q' packets to port 7878.  The ESPs will respond to you!

**Comment by cnlohr** [comment]
Oh, Also! Many web browsers get very confused and won't let the javascript keep going when trying to load the .png externally.  I've encoded the PNG into the webpage HTML itself.  I would imagine it could be done much more succinctly via an encoded ppm or something.  Just haven't messed with it yet.

**Pull request merged**
